name: "yolo"
platform: "onnxruntime_onnx"
max_batch_size: 8


instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 25200, 6 ]
  }
]
